package co.uk.directlinegroup.tt.step_definitions;

import co.uk.directlinegroup.tt.BaseStepDef;
import co.uk.directlinegroup.tt.utils.ClaimHandlingOperations;
import cucumber.api.PendingException;
import cucumber.api.java.en.And;

/**
 * Created by 324102 on 10/13/2017.
 */
public class ClaimHandling extends BaseStepDef{

    private ClaimHandlingOperations claimHandlingOperationsObj = new ClaimHandlingOperations();

    @And("^I should be able to verify the claim is not allocated to any handler before the FNOL process completed$")
    public void iShouldBeAbleToVerifyTheClaimIsNotAllocatedToAnyHandlerBeforeTheFNOLProcessCompleted() {
        claimHandlingOperationsObj.verifyClaimIsNotAllocatedToAnyClaimHandler();
    }
    @And("^The generic signature should be available in the email generated for '(.+)'$")
    public void verifySystemGeneratesAnAutomatedLetterAndalongWiththeClaimHandlerSignature(String event) throws Throwable {
        claimHandlingOperationsObj.validateGenericInAutoGeneratedLetter(event);
    }
}
